spring.application.name=vetclinic
spring.datasource.url=jdbc:h2:mem:vetclinic
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
logging.level.com.example.vetclinic=INFO
